---
- name: update apt
  apt: update_cache=yes cache_valid_time=86400

- name: install packages
  apt:
    state: latest
    package:
      - ufw
      - fail2ban
      - unattended-upgrades

- name: set up unattended upgrades
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: automatically remove unused dependencies
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
              regexp="Unattended-Upgrade::Remove-Unused-Dependencies"
              line="Unattended-Upgrade::Remove-Unused-Dependencies \"true\";"
              state=present
              create=yes

- name: ufw allow ssh traffic
  ufw: rule=allow port={{ ssh_port|string }} proto=tcp

- name: ufw allow http traffic
  ufw: rule=allow port=80 proto=tcp

- name: ufw allow https traffic
  ufw: rule=allow port=443 proto=tcp

- name: ufs deny everything else
  ufw: state=enabled policy=deny

- name: set up fail2ban
  command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
           creates=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: check su access
  command: dpkg-statoverride --list /bin/su
  register: su_statoverride
  changed_when: False
  failed_when: False

- name: remove existing su access override
  command: dpkg-statoverride --remove /bin/su
  when: su_statoverride.stdout and su_statoverride.stdout != "root sudo 4750 /bin/su"

- name: limit su access to sudo group
  command: dpkg-statoverride --update --add root sudo 4750 /bin/su
  when: not su_statoverride.stdout or su_statoverride.stdout != "root sudo 4750 /bin/su"

- name: secure shared memory
  lineinfile: dest=/etc/fstab
              regexp="/run/shm"
              line="none     /run/shm     tmpfs     defaults,noexec,nosuid,nodev     0     0"
              state=present
              backrefs=yes

- name: disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: allow ssh only for primary user
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^AllowUsers"
              line="AllowUsers {{ user }}"
              state=present
  notify: restart ssh

- name: disallow root ssh access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh

- name: set ssh port
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Port\s"
              line="Port {{ ssh_port }}"
              state=present
  notify: restart ssh
